apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: openwebui
    app.kubernetes.io/part-of: rhoai-demos
    app.kubernetes.io/component: application
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/openwebui-on-ocp.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-rhoai.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences: []
